#!/usr/bin/env python3
"""
validate_bugs.py — Confirm that classified failures are genuine Zipperposition bugs.

For each failure-triggering .p file, this script runs a series of checks:

  1. SYNTAX CHECK:   Is the .p file valid TPTP syntax?
                     (Run Zipperposition in normal mode — if it parses OK there,
                      the file itself is not malformed.)

  2. REPRODUCIBILITY: Does the same failure occur on 3 consecutive runs?
                     (Rules out transient/timing issues.)

  3. EXPECTED vs ACTUAL:
                     For --check-lambda-free, the expected response to an
                     out-of-fragment input is:
                       - stdout contains "Problem not in fragment" or similar
                       - exit code 0
                     An uncaught Failure(...) with exit code 1 is NOT the
                     expected rejection path — it is an internal error.

  4. CONTROL GROUP:  Run a known-good .p file (one that classifies as "ok")
                     to confirm the harness itself works correctly.

  5. DIFFERENTIAL:   Compare main harness vs lambda-free harness on same file.
                     If main harness succeeds but lambda-free throws Failure,
                     the bug is specifically in the lambda-free checking code.

Output: A validation_report.json with per-file verdicts.

Usage:
    python3 validate_bugs.py \
        --zp /path/to/zipperposition \
        --input-dir ~/fyp-isabelle-fuzz/unique_inputs \
        --classify-report ~/fyp-isabelle-fuzz/classify_results/classify_report.json \
        --output-dir ~/fyp-isabelle-fuzz/validation
"""

import argparse
import json
import subprocess
import sys
from pathlib import Path
from dataclasses import dataclass, asdict
from typing import Optional


@dataclass
class ValidationResult:
    file: str
    original_category: str

    # Check 1: Does normal mode parse the file OK?
    normal_mode_exit: int
    normal_mode_parses: bool          # True if no parse error in normal mode

    # Check 2: Reproducible across 3 runs?
    lambda_free_exits: list[int]      # exit codes from 3 runs
    reproducible: bool                # all 3 same category?

    # Check 3: What does the failure output look like?
    failure_message: Optional[str]    # the Failure(...) line
    is_uncaught_exception: bool       # True = internal error, not graceful rejection

    # Check 5: Differential — main harness vs lambda-free
    main_harness_exit: int
    differential: bool                # True = main OK but lambda-free fails

    # Final verdict
    verdict: str                      # "confirmed_bug" | "not_a_bug" | "inconclusive"
    reasoning: str


def run_zp(zp: str, filepath: Path, extra_args: list[str], timeout: int = 15):
    """Run Zipperposition and return (exit_code, stdout+stderr)."""
    cmd = [zp, "--input", "tptp", "--output", "none"] + extra_args + [str(filepath)]
    try:
        proc = subprocess.run(cmd, capture_output=True, text=True, timeout=timeout)
        return proc.returncode, proc.stdout + proc.stderr
    except subprocess.TimeoutExpired:
        return -1, "TIMEOUT"


def validate_file(zp: str, filepath: Path, original_category: str) -> ValidationResult:
    """Run all validation checks on a single file."""

    # ── Check 1: Normal mode parse ──
    normal_exit, normal_out = run_zp(zp, filepath, ["--steps", "1", "--timeout", "1"])
    normal_parses = "parse error" not in normal_out.lower()

    # ── Check 2: Reproducibility (3 runs of lambda-free) ──
    lf_exits = []
    lf_outputs = []
    for _ in range(3):
        ex, out = run_zp(zp, filepath, ["--check-lambda-free", "only"])
        lf_exits.append(ex)
        lf_outputs.append(out)

    reproducible = len(set(lf_exits)) == 1  # all same exit code

    # Extract failure message from first run
    failure_msg = None
    for line in lf_outputs[0].splitlines():
        if "Failure(" in line:
            failure_msg = line.strip()
            break

    # ── Check 3: Is it an uncaught exception? ──
    # Expected graceful rejection: "Problem not in fragment", exit 0
    # Bug indicator: Failure(...), exit 1
    is_uncaught = (
        failure_msg is not None
        and lf_exits[0] != 0
        and "Failure(" in lf_outputs[0]
    )

    # ── Check 5: Differential ──
    main_exit, _ = run_zp(zp, filepath, ["--steps", "1", "--timeout", "1"])
    differential = (main_exit == 0 and lf_exits[0] != 0)

    # ── Verdict ──
    if not normal_parses:
        # File itself has parse issues — bug might be in file, not ZP
        verdict = "inconclusive"
        reasoning = (
            "File triggers parse error in normal mode too. "
            "This could be a malformed TPTP file rather than a ZP bug. "
            "However, if the file was generated by Sledgehammer, "
            "the parse error itself may indicate a Sledgehammer export bug."
        )
    elif not reproducible:
        verdict = "inconclusive"
        reasoning = (
            f"Failure is not reproducible: exit codes across 3 runs = {lf_exits}. "
            "May be a timing or non-determinism issue."
        )
    elif is_uncaught and differential and reproducible:
        verdict = "confirmed_bug"
        reasoning = (
            "Normal mode parses the file successfully (valid TPTP). "
            "Main harness returns exit 0. "
            "Lambda-free check consistently throws an uncaught Failure() with exit 1. "
            "Expected behavior: graceful 'not in fragment' rejection. "
            "Actual: internal exception. This is a bug in the lambda-free checking code."
        )
    elif is_uncaught and reproducible:
        verdict = "confirmed_bug"
        reasoning = (
            "Lambda-free check consistently throws an uncaught Failure(). "
            "The exception is deterministic and not a graceful rejection. "
            "This indicates a bug in error handling."
        )
    else:
        verdict = "not_a_bug"
        reasoning = (
            f"Exit code = {lf_exits[0]}. "
            "No uncaught Failure() detected. "
            "This appears to be a normal rejection or expected behavior."
        )

    return ValidationResult(
        file=filepath.name,
        original_category=original_category,
        normal_mode_exit=normal_exit,
        normal_mode_parses=normal_parses,
        lambda_free_exits=lf_exits,
        reproducible=reproducible,
        failure_message=failure_msg,
        is_uncaught_exception=is_uncaught,
        main_harness_exit=main_exit,
        differential=differential,
        verdict=verdict,
        reasoning=reasoning,
    )


def main():
    parser = argparse.ArgumentParser(description="Validate classified failures as genuine bugs")
    parser.add_argument("--zp", required=True, help="Path to Zipperposition binary")
    parser.add_argument("--input-dir", required=True, help="Directory with .p files")
    parser.add_argument("--classify-report", required=True, help="Path to classify_report.json")
    parser.add_argument("--output-dir", default=str(Path.home() / "fyp-isabelle-fuzz" / "validation"))
    args = parser.parse_args()

    input_dir = Path(args.input_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    # Load classification report
    with open(args.classify_report) as f:
        report = json.load(f)

    # Find all files that had failures in lambda_free harness
    failure_files = {}
    ok_files = []
    for r in report["results"]:
        if r["harness"] != "lambda_free":
            continue
        if r["category"] == "ok":
            ok_files.append(r["file"])
        elif r["category"] not in ("ok", "timeout"):
            failure_files[r["file"]] = r["category"]

    print(f"[*] Found {len(failure_files)} failure files to validate")
    print(f"[*] Found {len(ok_files)} OK files for control group")

    # ── Validate each failure file ──
    results = []
    for i, (fname, category) in enumerate(sorted(failure_files.items()), 1):
        filepath = input_dir / fname
        if not filepath.exists():
            print(f"  [{i}/{len(failure_files)}] SKIP (file missing): {fname}")
            continue

        print(f"  [{i}/{len(failure_files)}] Validating: {fname} ({category})")
        result = validate_file(args.zp, filepath, category)
        results.append(result)
        print(f"    → {result.verdict}")

    # ── Control group: validate one OK file ──
    if ok_files:
        control_file = input_dir / ok_files[0]
        if control_file.exists():
            print(f"\n  [control] Validating OK file: {ok_files[0]}")
            control = validate_file(args.zp, control_file, "ok")
            results.append(control)
            print(f"    → {control.verdict}")

    # ── Write report ──
    json_path = output_dir / "validation_report.json"
    with open(json_path, "w") as f:
        json.dump([asdict(r) for r in results], f, indent=2)

    # ── Summary ──
    txt_path = output_dir / "validation_summary.txt"
    lines = [
        "=" * 60,
        "BUG VALIDATION SUMMARY",
        "=" * 60,
        "",
    ]

    confirmed = [r for r in results if r.verdict == "confirmed_bug"]
    inconclusive = [r for r in results if r.verdict == "inconclusive"]
    not_bugs = [r for r in results if r.verdict == "not_a_bug"]

    lines.append(f"Confirmed bugs:    {len(confirmed)}")
    lines.append(f"Inconclusive:      {len(inconclusive)}")
    lines.append(f"Not bugs:          {len(not_bugs)}")
    lines.append("")

    for r in results:
        lines.append(f"  [{r.verdict:16s}] {r.original_category:22s} {r.file}")
        lines.append(f"    Normal parse: {'OK' if r.normal_mode_parses else 'FAIL'} | "
                     f"Reproducible: {'YES' if r.reproducible else 'NO'} | "
                     f"Differential: {'YES' if r.differential else 'NO'}")
        lines.append(f"    {r.reasoning}")
        if r.failure_message:
            lines.append(f"    Failure: {r.failure_message[:150]}")
        lines.append("")

    txt_path.write_text("\n".join(lines) + "\n")

    print(f"\n{'='*60}")
    print(f"  Confirmed bugs:    {len(confirmed)}")
    print(f"  Inconclusive:      {len(inconclusive)}")
    print(f"  Not bugs:          {len(not_bugs)}")
    print(f"{'='*60}")
    print(f"[*] Full report:  {json_path}")
    print(f"[*] Summary:      {txt_path}")


if __name__ == "__main__":
    main()
