% /Applications/Isabelle2025.app/contrib/zipperposition-2.1-1/x86_64-darwin/zipperposition --input tptp --output tptp --timeout 5.000 --mode=ho-pragmatic --tptp-def-as-rewrite --rewrite-before-cnf=true --max-inferences=1 --ho-unif-max-depth=1 --ho-max-elims=0 --ho-max-app-projections=0 --ho-max-rigid-imitations=1 --ho-max-identifications=0 --boolean-reasoning=bool-hoist --bool-hoist-simpl=true --bool-select=LI --recognize-injectivity=true --ext-rules=ext-family --ext-rules-max-depth=1 --ho-choice-inst=true --ho-prim-enum=none --ho-elim-leibniz=0 --interpret-bool-funs=true --try-e="$E_HOME/eprover" --tmp-dir="$ISABELLE_TMP_PREFIX" --ho-unif-level=pragmatic-framework --select=bb+e-selection2 --post-cnf-lambda-lifting=true -q "4|prefer-sos|pnrefined(2,1,1,1,2,2,2)" -q "6|prefer-processed|conjecture-relative-struct(1.5,3.5,2,3)" -q "1|const|fifo" -q "4|prefer-ground|orient-lmax(2,1,2,1,1)" -q "4|defer-sos|conjecture-relative-struct(1,5,2,3)" --avatar=off --recognize-injectivity=true --ho-neg-ext=true --e-timeout=2 --ho-pattern-decider=true --ho-fixpoint-decider=true --e-max-derived=50 --ignore-orphans=true --e-auto=true --presaturate=true --e-call-point=0.1 /Users/xujiangjing/.isabelle/Isabelle2025/prob_zipperposition_1.p
% This file was generated by Isabelle (most likely Sledgehammer)2026-03-31 22:10:34.784
% Could-be-implicit typings (9)
thf(ty_n_t__Set__Oset_It__Product____Type__Oprod_It__Nat__Onat_Mt__Nat__Onat_J_J, type,
    set_Pr1986765409at_nat : $tType).
thf(ty_n_t__Set__Oset_It__Product____Type__Oprod_It__Int__Oint_Mt__Int__Oint_J_J, type,
    set_Pr1858794777nt_int : $tType).
thf(ty_n_t__Product____Type__Oprod_It__Nat__Onat_Mt__Nat__Onat_J, type,
    product_prod_nat_nat : $tType).
thf(ty_n_t__Product____Type__Oprod_It__Int__Oint_Mt__Int__Oint_J, type,
    product_prod_int_int : $tType).
thf(ty_n_t__Predicate__Opred_It__Product____Type__Ounit_J, type,
    pred_Product_unit : $tType).
thf(ty_n_t__List__Olist_It__Int__Oint_J, type,
    list_int : $tType).
thf(ty_n_t__Product____Type__Ounit, type,
    product_unit : $tType).
thf(ty_n_t__Nat__Onat, type,
    nat : $tType).
thf(ty_n_t__Int__Oint, type,
    int : $tType).

% Explicit typings (36)
thf(sy_c_HOL_OEx1_001t__Product____Type__Oprod_It__Int__Oint_Mt__Int__Oint_J, type,
    ex1_Pr315941075nt_int : (product_prod_int_int > $o) > $o).
thf(sy_c_HOL_OEx1_001t__Product____Type__Oprod_It__Nat__Onat_Mt__Nat__Onat_J, type,
    ex1_Pr240759323at_nat : (product_prod_nat_nat > $o) > $o).
thf(sy_c_Lattices_Osup__class_Osup_001t__Set__Oset_It__Product____Type__Oprod_It__Int__Oint_Mt__Int__Oint_J_J, type,
    sup_su60156141nt_int : set_Pr1858794777nt_int > set_Pr1858794777nt_int > set_Pr1858794777nt_int).
thf(sy_c_Lattices_Osup__class_Osup_001t__Set__Oset_It__Product____Type__Oprod_It__Nat__Onat_Mt__Nat__Onat_J_J, type,
    sup_su188126773at_nat : set_Pr1986765409at_nat > set_Pr1986765409at_nat > set_Pr1986765409at_nat).
thf(sy_c_Nunchaku_Ormember_001t__Product____Type__Oprod_It__Int__Oint_Mt__Int__Oint_J, type,
    rmembe1308891511nt_int : set_Pr1858794777nt_int > product_prod_int_int > $o).
thf(sy_c_Nunchaku_Ormember_001t__Product____Type__Oprod_It__Nat__Onat_Mt__Nat__Onat_J, type,
    rmembe1233709759at_nat : set_Pr1986765409at_nat > product_prod_nat_nat > $o).
thf(sy_c_Orderings_Obot__class_Obot_001t__Predicate__Opred_It__Product____Type__Ounit_J, type,
    bot_bo826684087t_unit : pred_Product_unit).
thf(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_It__Product____Type__Oprod_It__Int__Oint_Mt__Int__Oint_J_J, type,
    bot_bo2002416005nt_int : set_Pr1858794777nt_int).
thf(sy_c_Orderings_Obot__class_Obot_001t__Set__Oset_It__Product____Type__Oprod_It__Nat__Onat_Mt__Nat__Onat_J_J, type,
    bot_bo2130386637at_nat : set_Pr1986765409at_nat).
thf(sy_c_Predicate_Osingle_001t__Product____Type__Ounit, type,
    single_Product_unit : product_unit > pred_Product_unit).
thf(sy_c_Predicate__Compile_Ocontains_001t__Product____Type__Oprod_It__Int__Oint_Mt__Int__Oint_J, type,
    predic1876118929nt_int : set_Pr1858794777nt_int > product_prod_int_int > $o).
thf(sy_c_Predicate__Compile_Ocontains_001t__Product____Type__Oprod_It__Nat__Onat_Mt__Nat__Onat_J, type,
    predic1800937177at_nat : set_Pr1986765409at_nat > product_prod_nat_nat > $o).
thf(sy_c_Predicate__Compile_Ocontains__pred_001t__Product____Type__Oprod_It__Int__Oint_Mt__Int__Oint_J, type,
    predic769235664nt_int : set_Pr1858794777nt_int > product_prod_int_int > pred_Product_unit).
thf(sy_c_Predicate__Compile_Ocontains__pred_001t__Product____Type__Oprod_It__Nat__Onat_Mt__Nat__Onat_J, type,
    predic694053912at_nat : set_Pr1986765409at_nat > product_prod_nat_nat > pred_Product_unit).
thf(sy_c_Product__Type_OPair_001t__Int__Oint_001t__Int__Oint, type,
    product_Pair_int_int : int > int > product_prod_int_int).
thf(sy_c_Product__Type_OPair_001t__Nat__Onat_001t__Nat__Onat, type,
    product_Pair_nat_nat : nat > nat > product_prod_nat_nat).
thf(sy_c_Product__Type_OUnity, type,
    product_Unity : product_unit).
thf(sy_c_Product__Type_Oprod_Ocase__prod_001t__Int__Oint_001t__Int__Oint_001_Eo, type,
    produc13737234_int_o : (int > int > $o) > product_prod_int_int > $o).
thf(sy_c_Product__Type_Oprod_Ocase__prod_001t__Nat__Onat_001t__Nat__Onat_001_Eo, type,
    produc949581770_nat_o : (nat > nat > $o) > product_prod_nat_nat > $o).
thf(sy_c_Relation_OId_001t__Int__Oint, type,
    id_int : set_Pr1858794777nt_int).
thf(sy_c_Relation_OId_001t__Nat__Onat, type,
    id_nat : set_Pr1986765409at_nat).
thf(sy_c_Set_OCollect_001t__Product____Type__Oprod_It__Int__Oint_Mt__Int__Oint_J, type,
    collec82830756nt_int : (product_prod_int_int > $o) > set_Pr1858794777nt_int).
thf(sy_c_Set_OCollect_001t__Product____Type__Oprod_It__Nat__Onat_Mt__Nat__Onat_J, type,
    collec7649004at_nat : (product_prod_nat_nat > $o) > set_Pr1986765409at_nat).
thf(sy_c_Set_Oinsert_001t__Product____Type__Oprod_It__Int__Oint_Mt__Int__Oint_J, type,
    insert346776969nt_int : product_prod_int_int > set_Pr1858794777nt_int > set_Pr1858794777nt_int).
thf(sy_c_Set_Oinsert_001t__Product____Type__Oprod_It__Nat__Onat_Mt__Nat__Onat_J, type,
    insert271595217at_nat : product_prod_nat_nat > set_Pr1986765409at_nat > set_Pr1986765409at_nat).
thf(sy_c_Transitive__Closure_Ortrancl_001t__Int__Oint, type,
    transi134874473cl_int : set_Pr1858794777nt_int > set_Pr1858794777nt_int).
thf(sy_c_Transitive__Closure_Ortrancl_001t__Nat__Onat, type,
    transi1645084429cl_nat : set_Pr1986765409at_nat > set_Pr1986765409at_nat).
thf(sy_c_Transitive__Closure_Ortranclp_001t__Int__Oint, type,
    transi1498689441lp_int : (int > int > $o) > int > int > $o).
thf(sy_c_Transitive__Closure_Ortranclp_001t__Nat__Onat, type,
    transi861415749lp_nat : (nat > nat > $o) > nat > nat > $o).
thf(sy_c_Transitive__Closure_Otrancl_001t__Int__Oint, type,
    transi286409547cl_int : set_Pr1858794777nt_int > set_Pr1858794777nt_int).
thf(sy_c_Transitive__Closure_Otrancl_001t__Nat__Onat, type,
    transi1796619503cl_nat : set_Pr1986765409at_nat > set_Pr1986765409at_nat).
thf(sy_c_Transitive__Closure_Otranclp_001t__Int__Oint, type,
    transi1346202175lp_int : (int > int > $o) > int > int > $o).
thf(sy_c_Transitive__Closure_Otranclp_001t__Nat__Onat, type,
    transi708928483lp_nat : (nat > nat > $o) > nat > nat > $o).
thf(sy_c_member_001t__Product____Type__Oprod_It__Int__Oint_Mt__Int__Oint_J, type,
    member776767074nt_int : product_prod_int_int > set_Pr1858794777nt_int > $o).
thf(sy_c_member_001t__Product____Type__Oprod_It__Nat__Onat_Mt__Nat__Onat_J, type,
    member701585322at_nat : product_prod_nat_nat > set_Pr1986765409at_nat > $o).
thf(sy_v_s, type,
    s : list_int).

% Relevant facts (20)
thf(fact_0_rmember__def, axiom,
    ((rmembe1233709759at_nat = (^[A : set_Pr1986765409at_nat]: (^[X : product_prod_nat_nat]: (member701585322at_nat @ X @ A))))), [], [isabelle_non_rec_def, isabelle_rank(900)]). % rmember_def
thf(fact_1_rmember__def, axiom,
    ((rmembe1308891511nt_int = (^[A : set_Pr1858794777nt_int]: (^[X : product_prod_int_int]: (member776767074nt_int @ X @ A))))), [], [isabelle_non_rec_def, isabelle_rank(1035)]). % rmember_def
thf(fact_2_Predicate__Compile_OcontainsI, axiom,
    ((![X2 : product_prod_nat_nat, A2 : set_Pr1986765409at_nat]: ((member701585322at_nat @ X2 @ A2) => (predic1800937177at_nat @ A2 @ X2)))), [], [isabelle_rank(1170)]). % Predicate_Compile.containsI
thf(fact_3_Predicate__Compile_OcontainsI, axiom,
    ((![X2 : product_prod_int_int, A2 : set_Pr1858794777nt_int]: ((member776767074nt_int @ X2 @ A2) => (predic1876118929nt_int @ A2 @ X2)))), [], [isabelle_rank(1305)]). % Predicate_Compile.containsI
thf(fact_4_Predicate__Compile_OcontainsE, axiom,
    ((![A2 : set_Pr1986765409at_nat, X2 : product_prod_nat_nat]: ((predic1800937177at_nat @ A2 @ X2) => (member701585322at_nat @ X2 @ A2)))), [], [isabelle_rank(1440)]). % Predicate_Compile.containsE
thf(fact_5_Predicate__Compile_OcontainsE, axiom,
    ((![A2 : set_Pr1858794777nt_int, X2 : product_prod_int_int]: ((predic1876118929nt_int @ A2 @ X2) => (member776767074nt_int @ X2 @ A2)))), [], [isabelle_rank(1575)]). % Predicate_Compile.containsE
thf(fact_6_contains__pred__def, axiom,
    ((predic694053912at_nat = (^[A : set_Pr1986765409at_nat]: (^[X : product_prod_nat_nat]: $ite((member701585322at_nat @ X @ A), (single_Product_unit @ product_Unity), bot_bo826684087t_unit))))), [], [isabelle_non_rec_def, isabelle_rank(1710)]). % contains_pred_def
thf(fact_7_contains__pred__def, axiom,
    ((predic769235664nt_int = (^[A : set_Pr1858794777nt_int]: (^[X : product_prod_int_int]: $ite((member776767074nt_int @ X @ A), (single_Product_unit @ product_Unity), bot_bo826684087t_unit))))), [], [isabelle_non_rec_def, isabelle_rank(1845)]). % contains_pred_def
thf(fact_8_contains__def, axiom,
    ((predic1800937177at_nat = (^[A : set_Pr1986765409at_nat]: (^[X : product_prod_nat_nat]: (member701585322at_nat @ X @ A))))), [], [isabelle_non_rec_def, isabelle_rank(1980)]). % contains_def
thf(fact_9_contains__def, axiom,
    ((predic1876118929nt_int = (^[A : set_Pr1858794777nt_int]: (^[X : product_prod_int_int]: (member776767074nt_int @ X @ A))))), [], [isabelle_non_rec_def, isabelle_rank(2115)]). % contains_def
thf(fact_10_Nitpick_Otranclp__unfold, axiom,
    ((transi1346202175lp_int = (^[R : int > int > $o]: (^[A3 : int]: (^[B : int]: (member776767074nt_int @ (product_Pair_int_int @ A3 @ B) @ (transi286409547cl_int @ (collec82830756nt_int @ (produc13737234_int_o @ R))))))))), [], [isabelle_rank(2250)]). % Nitpick.tranclp_unfold
thf(fact_11_Nitpick_Otranclp__unfold, axiom,
    ((transi708928483lp_nat = (^[R : nat > nat > $o]: (^[A3 : nat]: (^[B : nat]: (member701585322at_nat @ (product_Pair_nat_nat @ A3 @ B) @ (transi1796619503cl_nat @ (collec7649004at_nat @ (produc949581770_nat_o @ R))))))))), [], [isabelle_rank(2385)]). % Nitpick.tranclp_unfold
thf(fact_12_Nitpick_Ortranclp__unfold, axiom,
    ((transi861415749lp_nat = (^[R : nat > nat > $o]: (^[A3 : nat]: (^[B : nat]: (((A3 = B)) | ((transi708928483lp_nat @ R @ A3 @ B)))))))), [], [isabelle_rank(2520)]). % Nitpick.rtranclp_unfold
thf(fact_13_Nitpick_Ortranclp__unfold, axiom,
    ((transi1498689441lp_int = (^[R : int > int > $o]: (^[A3 : int]: (^[B : int]: (((A3 = B)) | ((transi1346202175lp_int @ R @ A3 @ B)))))))), [], [isabelle_rank(2655)]). % Nitpick.rtranclp_unfold
thf(fact_14_Nitpick_Ortrancl__unfold, axiom,
    ((transi1645084429cl_nat = (^[R : set_Pr1986765409at_nat]: (sup_su188126773at_nat @ (transi1796619503cl_nat @ R) @ id_nat)))), [], [isabelle_rank(2790)]). % Nitpick.rtrancl_unfold
thf(fact_15_Nitpick_Ortrancl__unfold, axiom,
    ((transi134874473cl_int = (^[R : set_Pr1858794777nt_int]: (sup_su60156141nt_int @ (transi286409547cl_int @ R) @ id_int)))), [], [isabelle_rank(2925)]). % Nitpick.rtrancl_unfold
thf(fact_16_norm__frac_Ocases, axiom,
    ((![X2 : product_prod_int_int]: (~ ((![A4 : int, B2 : int]: (X2 != (product_Pair_int_int @ A4 @ B2))))))), [], [isabelle_rank(3060)]). % norm_frac.cases
thf(fact_17_nat__gcd_Ocases, axiom,
    ((![X2 : product_prod_nat_nat]: (~ ((![X3 : nat, Y : nat]: (X2 != (product_Pair_nat_nat @ X3 @ Y))))))), [], [isabelle_rank(3195)]). % nat_gcd.cases
thf(fact_18_Nitpick_OEx1__unfold, axiom,
    ((ex1_Pr240759323at_nat = (^[P : product_prod_nat_nat > $o]: (?[X : product_prod_nat_nat]: ((collec7649004at_nat @ P) = (insert271595217at_nat @ X @ bot_bo2130386637at_nat)))))), [], [isabelle_rank(3330)]). % Nitpick.Ex1_unfold
thf(fact_19_Nitpick_OEx1__unfold, axiom,
    ((ex1_Pr315941075nt_int = (^[P : product_prod_int_int > $o]: (?[X : product_prod_int_int]: ((collec82830756nt_int @ P) = (insert346776969nt_int @ X @ bot_bo2002416005nt_int)))))), [], [isabelle_rank(3465)]). % Nitpick.Ex1_unfold

% Conjectures (1)
thf(conj_0, conjecture,
    ((s = s))).
